### ISSUE TITLE
Publish symbols to dotnet.myget.org along with signed packages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#124]
This is two part work
- As part of publishing signed packages, we should publish symbols with them.
- As part of Coherence-Signed, we need to create timestamp free versions of symbols packages. This will let us publish the right package versions to the feed.

**Comment by muratg** [comment]
cc @Eilon

**Comment by mrahhal** [comment]
Hey, I've been searching for quite a bit, and I can't seem to find where the symbols (for aspnetcore 1) are stored. I tried some of the following:
- https://nuget.smbsrc.net
- https://dotnet.myget.org/F/aspnetcore-release/symbols
- http://msdl.microsoft.com/download/symbols

Are there up-to-date instructions on this anywhere?

**Comment by Eilon** [comment]
We have the symbols for ASP.NET Core 1.1 and 2.0 on the Microsoft public symbol servers. We haven't done symbol packages.

**Comment by mrahhal** [comment]
Forgive my ignorance, but what does this exactly mean? 😅 
I've been looking for information about this everywhere, but most date to a very long time ago.

**Comment by pranavkm** [comment]
Symbol nupkgs contain a copy of the sources that were built along with the pdb. We published it for the 1.0.0 release (for instance https://dotnet.myget.org/F/aspnetcore-master/symbols/Microsoft.AspNetCore.Mvc/1.0.0) but haven't' since. For the 1.1 and 2.0 release, we have pdbs in the symbol server.

**Comment by Eilon** [comment]
@mrahhal the Microsoft Public Symbol Server is at `https://msdl.microsoft.com/download/symbols` - make sure that's listed in your Visual Studio debugger settings for symbols.

**Comment by mrahhal** [comment]
@Eilon I have that, but still not working for some reason. Maybe it's my setup (I made sure to disable "Enable Just my Code").

"It's not working" means that I added a breakpoint at `var host = new WebHostBuilder()` to start with, stepping into did not "step into" WebHostBuilder. (I tried in several other places)

**Comment by Eilon** [comment]
Ah, the symbols don't enable stepping into source - they do enable things such as line numbers and more details about local variables.

We plan to add source stepping in the near future, we just haven't gotten to it yet.

**Comment by mrahhal** [comment]
Oh.. Makes sense now. That would be really great.
